### ISSUE TITLE
注意全域變數問題

### ISSUE THREAD

**Issue by azole** [Roger103109/node-workshop#1]
https://github.com/Roger103109/node-workshop/blob/0065b068ebef290ff04b40c56506f48531f0d9e6/basic/sum.js#L6

這邊的 i 最好也加上 let 去宣告，讓這個 i 變數的範疇僅止於當前區塊，沒有加上 let 的話，這個 i 就會變成一個全域變數，這在未來容易有 bug 或不好除錯。

這是你的程式碼，我在最後一行加上了一個 console.log(i)，你可以比較看看，for 迴圈這邊有沒有加上 let 的差別，然後回覆給我？

```javascript
function sum(n){
    let totalresult=0;
    for(i=0;i<=n;i++){
        totalresult=i+totalresult;
    }
    return totalresult;
};
console.log(sum(1));
console.log(sum(10));
// 加上這行做個測試
console.log(i);
```

**Comment by Roger103109** [comment]
加let後 i 只會在function sum(n){}  裡面
